# Generated by Django 5.0.6 on 2024-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('classic', 'classic'), ('Fiction', 'fiction'), ('Fantasy', 'fantasy'), ('Mystery', 'mystery'), ('Romance', 'romance'), ('Biography', 'biography'), ('Science Fiction', 'scienceFiction'), ('Historical Fiction', 'historicalFiction')], max_length=50),
        ),
    ]
