# Generated by Django 5.0.6 on 2024-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Ciction', 'Fiction'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Biography', 'Biography'), ('Science Fiction', 'Science Fiction'), ('Historical Fiction', 'Historical Fiction')], max_length=50),
        ),
    ]
