# Generated by Django 5.0.6 on 2024-06-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_borrower_alter_book_category_borrow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='return_date',
        ),
    ]
